/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author CRISTIAN
 */
public class RegistrarClientes extends javax.swing.JFrame {
    
    String user;
    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarClientes() {
        initComponents();
        user = Login.user;
        
        setSize(600, 600);
        setResizable(false);
        setTitle("Registrar Clientes - Sesión de " + user);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JTextField();
        txt_EmailCliente = new javax.swing.JTextField();
        txt_TelefonoCliente = new javax.swing.JTextField();
        txt_DireccionCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("Registrar clientes");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        txt_NombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 240, 30));

        txt_EmailCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_EmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 240, 30));

        txt_TelefonoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_TelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 240, 30));

        txt_DireccionCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_DireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 240, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dirección:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, 100));

        jLabel2.setText("Registrar cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int validacion = 0;
        String nombre, mail, telefono, direccion;
        
        nombre = txt_NombreCliente.getText().trim();
        mail = txt_EmailCliente.getText().trim();
        telefono = txt_TelefonoCliente.getText().trim();
        direccion = txt_DireccionCliente.getText().trim();
        
        if(nombre.equals("")){
            txt_NombreCliente.setBackground(Color.RED);
            validacion++;
        }
        if(mail.equals("")){
            txt_EmailCliente.setBackground(Color.RED);
            validacion++;
        }
        if(telefono.equals("")){
            txt_TelefonoCliente.setBackground(Color.RED);
            validacion++;
        }
        if(direccion.equals("")){
            txt_DireccionCliente.setBackground(Color.RED);
            validacion++;
        }
        
        if (validacion == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into clientes values (?,?,?,?,?,?)");
                
                pst.setInt(1, 0);
                pst.setString(2, nombre);
                pst.setString(3, mail);
                pst.setString(4, telefono);
                pst.setString(5, direccion);
                pst.setString(6, user);
                
                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                txt_NombreCliente.setBackground(Color.GREEN);
                txt_EmailCliente.setBackground(Color.GREEN);
                txt_TelefonoCliente.setBackground(Color.GREEN);
                txt_DireccionCliente.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
                this.dispose();
                
                
            } catch (SQLException e) {
                System.err.println("Error al registrar cliente " + e);
                JOptionPane.showMessageDialog(null, "Error al registrar cliente, contacte al administrador.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_DireccionCliente;
    private javax.swing.JTextField txt_EmailCliente;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_TelefonoCliente;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
        txt_NombreCliente.setText("");
        txt_EmailCliente.setText("");
        txt_TelefonoCliente.setText("");
        txt_DireccionCliente.setText("");
    }
}
