package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author CRISTIAN
 */
public class RegistrarUsuarios extends javax.swing.JFrame {

    String user;
    int permisos_cmb, validacion = 0;
    String nombre, mail, telefono, username, pass, permisos_string = "";
    public RegistrarUsuarios() {
        initComponents();
        user = Login.user;
        setTitle("Registro de nuevo usuario - Sesión de " + user);
        setSize(600, 600);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Telefono = new javax.swing.JTextField();
        cmb_Niveles = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE USUARIOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 320, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        txt_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        txt_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        txt_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 190, -1));

        cmb_Niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(cmb_Niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        txt_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Permisos de:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 100, 100));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

        mail = txt_Email.getText().trim();
        username = txt_Username.getText().trim();
        pass = txt_Password.getText().trim();
        nombre = txt_Nombre.getText().trim();
        telefono = txt_Telefono.getText().trim();
        permisos_cmb = cmb_Niveles.getSelectedIndex() + 1;

        Marcar_vacios();
        
        if (permisos_cmb == 1) {
            permisos_string = "Administrador";
        } else if (permisos_cmb == 2) {
            permisos_string = "Capturista";
        } else if (permisos_cmb == 3) {
            permisos_string = "Tecnico";
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select username from usuarios where username = '" + username + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Username.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible.");
                cn.close();
            } else {
                cn.close();
                if (validacion == 0) {
                    try {
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement("insert into usuarios values (?,?,?,?,?,?,?,?,?)");
                        pst2.setInt(1, 0);
                        pst2.setString(2, nombre);
                        pst2.setString(3, mail);
                        pst2.setString(4, telefono);
                        pst2.setString(5, username);
                        pst2.setString(6, pass);
                        pst2.setString(7, permisos_string);
                        pst2.setString(8, "Activo");
                        pst2.setString(9, user);

                        pst2.executeUpdate();
                        cn2.close();
                        
                        Limpiar();
                        
                        JOptionPane.showMessageDialog(null, "Registro exitoso.");
                        this.dispose();

                    } catch (SQLException e) {
                        System.err.println("Error en registrar usuario " + e);
                        JOptionPane.showMessageDialog(null, "Error al comparar usuario, Contácte al administrador.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor complete todos los datos.");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usuario. " + e);
            JOptionPane.showMessageDialog(null, "ERROR al comparar usuario, contacte al administrador.");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Niveles;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
    public void Limpiar(){
        txt_Email.setText("");
        txt_Nombre.setText("");
        txt_Password.setText("");
        txt_Telefono.setText("");
        txt_Username.setText("");
        cmb_Niveles.setSelectedIndex(0);
    }
    public void Marcar_vacios(){
        if (mail.equals("")) {
            txt_Email.setBackground(Color.RED);
            validacion++;
        }else{
            txt_Email.setBackground(Color.WHITE);
        }
        if (username.equals("")) {
            txt_Username.setBackground(Color.RED);
            validacion++;
        }else{
            txt_Username.setBackground(Color.WHITE);
        }
        if (pass.equals("")) {
            txt_Password.setBackground(Color.RED);
            validacion++;
        }else{
            txt_Password.setBackground(Color.WHITE);
        }
        if (nombre.equals("")) {
            txt_Nombre.setBackground(Color.RED);
            validacion++;
        }else{
            txt_Nombre.setBackground(Color.WHITE);
        }
        if (telefono.equals("")) {
            txt_Telefono.setBackground(Color.RED);
            validacion++;
        }else{
            txt_Telefono.setBackground(Color.WHITE);
        }
    }
}
